version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/rmrn
hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 120
      runas: root