name: github-action-hit-codedeploy

on:
  push:
    branches:
      - main

env:
  CODEDEPLOY_NAME: app
  CODEDEPLOY_GROUP: app

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Code Deploy
        run: aws deploy create-deployment --application-name $CODEDEPLOY_NAME --deployment-group-name $CODEDEPLOY_GROUP --deployment-config-name CodeDeployDefault.AllAtOnce

