name: Test Backend Pull Request

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  files-changed:
    name: Determine if files changed
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - backend/**
              - .github/workflows/backend-**.yml
    outputs:
      filesChanged: ${{ steps.changes.outputs.src }}

  test:
    needs: [files-changed]
    if: needs.files-changed.outputs.filesChanged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend

      - name: Run tests
        run: pytest
        working-directory: ./backend


